
------------------------
-- [ActivityLogType]
------------------------
INSERT INTO [dbo].[ActivityLogType]
(
[ActivityLogTypeName]
      ,[Description]
      ,[IsActive]
      ,[IsDeleted]
      ,[EnteredBy]
      ,[DisplayOrder]
      ,[CreatedOnUtc]
      ,[UpdatedOnUtc]
)
SELECT [ActivityLogTypeName]
      ,[Description]
      ,[IsActive]
      ,[IsDeleted]
      ,[EnteredBy]
      ,[DisplayOrder]
      ,[CreatedOnUtc]
      ,[UpdatedOnUtc]
FROM [Workforce2].[dbo].[ActivityLogType]


-------------------------
--[Intersection]
-------------------------
INSERT INTO [dbo].[Intersection]
(
[IntersectionName],
[Note],
[IsActive],
[IsDeleted],
[EnteredBy],
[DisplayOrder],
[CreatedOnUtc],
[UpdatedOnUtc]
)
SELECT [IntersectionName],
[Note],
[IsActive],
[IsDeleted],
[EnteredBy],
[DisplayOrder],
[CreatedOnUtc],
[UpdatedOnUtc]
FROM [Workforce2].[dbo].[Intersection]


------------------------
-- [Candidate]
------------------------
SET IDENTITY_INSERT [dbo].[Candidate] ON
INSERT INTO [dbo].[Candidate]
      (
      [Id]
      ,[CandidateGuid]
      ,[Username]
      ,[Password]
      ,[PasswordFormatId]
      ,[PasswordSalt]
      ,[PasswordResetToken]
      ,[TokenExpiryDate]
      ,[EmployeeId]
      ,[Email]
      ,[Email2]
      ,[SalutationId]
      ,[GenderId]
      ,[EthnicTypeId]
      ,[VetranTypeId]
      ,[SourceId]
      ,[FirstName]
      ,[LastName]
      ,[MiddleName]
      ,[HomePhone]
      ,[MobilePhone]
      ,[EmergencyPhone]
      ,[WebSite]
      ,[BestTimetoCall]
      ,[DisabilityStatus]
      ,[IsHot]
      ,[IsActive]
      ,[IsBanned]
      ,[IsDeleted]
      ,[Entitled]
      ,[CanRelocate]
      ,[JobTitle]
      ,[Education]
      ,[Education2]
      ,[DateAvailable]
      ,[CurrentEmployer]
      ,[CurrentPay]
      ,[DesiredPay]
      ,[ShiftId]
      ,[TransportationId]
      ,[MajorIntersection1]
      ,[MajorIntersection2]
      ,[PreferredWorkLocation]
      ,[BirthDate]
      ,[SocialInsuranceNumber]
      ,[Note]
      ,[EnteredBy]
      ,[OwnerId]
      ,[FranchiseId]
      ,[SearchKeys]
      ,[CreatedOnUtc]
      ,[UpdatedOnUtc]
      )
SELECT 
	[Id]
      ,[CandidateGuid]
      ,[Username]
      ,[Password]
      ,[PasswordFormatId]
      ,[PasswordSalt]
      ,[PasswordResetToken]
      ,[TokenExpiryDate]
      ,[EmployeeId]
      ,[Email]
      ,[Email2]
      ,[SalutationId]
      ,[GenderId]
      ,[EthnicTypeId]
      ,[VetranTypeId]
      ,[SourceId]
      ,[FirstName]
      ,[LastName]
      ,[MiddleName]
      ,[HomePhone]
      ,[MobilePhone]
      ,[EmergencyPhone]
      ,[WebSite]
      ,[BestTimetoCall]
      ,[DisabilityStatus]
      ,[IsHot]
      ,[IsActive]
      ,[IsBanned]
      ,[IsDeleted]
      ,[Entitled]
      ,[CanRelocate]
      ,[JobTitle]
      ,[Education]
      ,[Education2]
      ,[DateAvailable]
      ,[CurrentEmployer]
      ,[CurrentPay]
      ,[DesiredPay]
      ,[ShiftId]
      ,[TransportationId]
      ,[MajorIntersection1]
      ,[MajorIntersection2]
      ,[PreferredWorkLocation]
      ,[BirthDate]
      ,[SocialInsuranceNumber]
      ,[Note]
      ,[EnteredBy]
      ,[OwnerId]
      ,[FranchiseId]
      ,[SearchKeys]
      ,[CreatedOnUtc]
      ,[UpdatedOnUtc]
FROM [Workforce2].[dbo].[Candidate]

SET IDENTITY_INSERT [dbo].[Candidate] OFF
GO

------------------------
-- [CandidateAddress]
------------------------
SET IDENTITY_INSERT [dbo].[CandidateAddress] ON
INSERT INTO [dbo].[CandidateAddress]
      (
      [Id]
      ,[CandidateId]
      ,[AddressTypeId]
      ,[AddressName]
      ,[UnitNumber]
      ,[AddressLine1]
      ,[AddressLine2]
      ,[AddressLine3]
      ,[AddressLine4]
      ,[AddressLine5]
      ,[City]
      ,[StateProvince]
      ,[Country]
      ,[PostalCode]
      ,[Note]
      ,[IsActive]
      ,[IsDeleted]
      ,[CreatedOnUtc]
      ,[UpdatedOnUtc]
      )
SELECT 
       [Id]
      ,[CandidateId]
      ,[AddressTypeId]
      ,[AddressName]
      ,[UnitNumber]
      ,[AddressLine1]
      ,[AddressLine2]
      ,[AddressLine3]
      ,[AddressLine4]
      ,[AddressLine5]
      ,[City]
      ,[StateProvince]
      ,[Country]
      ,[PostalCode]
      ,[Note]
      ,[IsActive]
      ,[IsDeleted]
      ,[CreatedOnUtc]
      ,[UpdatedOnUtc]
      FROM [Workforce2].[dbo].[CandidateAddress]
GO
SET IDENTITY_INSERT [dbo].[CandidateAddress] OFF


INSERT INTO [dbo].[Company]
      (
      [CompanyGuid]
      ,[CompanyName]
      ,[WebSite]
      ,[KeyTechnology]
      ,[Note]
      ,[IsHot]
      ,[IsActive]
      ,[IsDeleted]
      ,[IsAdmin]
      ,[OwnerId]
      ,[EnteredBy]
      ,[FranchiseId]
      ,[DisplayOrder]
      ,[CreatedOnUtc]
      ,[UpdatedOnUtc])
SELECT [CompanyGuid]
      ,[CompanyName]
      ,[WebSite]
      ,[KeyTechnology]
      ,[Note]
      ,[IsHot]
      ,[IsActive]
      ,[IsDeleted]
      ,[IsAdmin]
      ,[OwnerId]
      ,[EnteredBy]
      ,[FranchiseId]
      ,[DisplayOrder]
      ,[CreatedOnUtc]
      ,[UpdatedOnUtc]
       FROM [Workforce2].[dbo].[Company]
       
SET IDENTITY_INSERT [dbo].[JobOrder] ON
INSERT INTO [dbo].[JobOrder]
([Id]
      ,[JobOrderGuid]
      ,[CompanyId]
      ,[CompanyLocationId]
      ,[CompanyDepartmentId]
      ,[CompanyContactId]
      ,[CompanyJobNumber]
      ,[JobTitle]
      ,[JobDescription]
      ,[HiringDurationExpiredDate]
      ,[EstimatedFinishingDate]
      ,[EstimatedMargin]
      ,[StartDate]
      ,[EndDate]
      ,[StartTime]
      ,[EndTime]
      ,[SchedulePolicyId]
      ,[JobOrderTypeId]
      ,[Salary]
      ,[JobOrderStatusId]
      ,[JobOrderCategoryId]
      ,[CompanyBillingRateId]
      ,[OpeningNumber]
      ,[ShiftId]
      ,[ShiftSchedule]
      ,[Supervisor]
      ,[HoursPerWeek]
      ,[Note]
      ,[RequireSafeEquipment]
      ,[RequireSafetyShoe]
      ,[IsInternalPosting]
      ,[IsPublished]
      ,[IsHot]
      ,[IsDeleted]
      ,[RecruiterId]
      ,[OwnerId]
      ,[FranchiseId]
      ,[EnteredBy]
      ,[CreatedOnUtc]
      ,[UpdatedOnUtc])
SELECT [Id]
      ,[JobOrderGuid]
      ,[CompanyId]
      ,[CompanyLocationId]
      ,[CompanyDepartmentId]
      ,[CompanyContactId]
      ,[CompanyJobNumber]
      ,[JobTitle]
      ,[JobDescription]
      ,[HiringDurationExpiredDate]
      ,[EstimatedFinishingDate]
      ,[EstimatedMargin]
      ,[StartDate]
      ,[EndDate]
      ,[StartTime]
      ,[EndTime]
      ,[SchedulePolicyId]
      ,[JobOrderTypeId]
      ,[Salary]
      ,[JobOrderStatusId]
      ,[JobOrderCategoryId]
      ,[CompanyBillingRateId]
      ,[OpeningNumber]
      ,[ShiftId]
      ,[ShiftSchedule]
      ,[Supervisor]
      ,[HoursPerWeek]
      ,[Note]
      ,[RequireSafeEquipment]
      ,[RequireSafetyShoe]
      ,[IsInternalPosting]
      ,[IsPublished]
      ,[IsHot]
      ,[IsDeleted]
      ,[RecruiterId]
      ,[OwnerId]
      ,[FranchiseId]
      ,[EnteredBy]
      ,[CreatedOnUtc]
      ,[UpdatedOnUtc]
      FROM [Workforce2].[dbo].[JobOrder]
SET IDENTITY_INSERT [dbo].[JobOrder] OFF