//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wfm.Admin.ClientServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AuthenticationResult", Namespace="http://schemas.datacontract.org/2004/07/WcfServices")]
    [System.SerializableAttribute()]
    public partial class AuthenticationResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsDelegateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsPasswordExpiredField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsValidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SessionIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsDelegate {
            get {
                return this.IsDelegateField;
            }
            set {
                if ((this.IsDelegateField.Equals(value) != true)) {
                    this.IsDelegateField = value;
                    this.RaisePropertyChanged("IsDelegate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsPasswordExpired {
            get {
                return this.IsPasswordExpiredField;
            }
            set {
                if ((this.IsPasswordExpiredField.Equals(value) != true)) {
                    this.IsPasswordExpiredField = value;
                    this.RaisePropertyChanged("IsPasswordExpired");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsValid {
            get {
                return this.IsValidField;
            }
            set {
                if ((this.IsValidField.Equals(value) != true)) {
                    this.IsValidField = value;
                    this.RaisePropertyChanged("IsValid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SessionId {
            get {
                return this.SessionIdField;
            }
            set {
                if ((object.ReferenceEquals(this.SessionIdField, value) != true)) {
                    this.SessionIdField = value;
                    this.RaisePropertyChanged("SessionId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PagedListResultOfTimeSheetHpUzpNkN", Namespace="http://schemas.datacontract.org/2004/07/WcfServices")]
    [System.SerializableAttribute()]
    public partial class PagedListResultOfTimeSheetHpUzpNkN : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Wfm.Admin.ClientServiceReference.TimeSheet[] ItemsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long TotalCountField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Wfm.Admin.ClientServiceReference.TimeSheet[] Items {
            get {
                return this.ItemsField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemsField, value) != true)) {
                    this.ItemsField = value;
                    this.RaisePropertyChanged("Items");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long TotalCount {
            get {
                return this.TotalCountField;
            }
            set {
                if ((this.TotalCountField.Equals(value) != true)) {
                    this.TotalCountField = value;
                    this.RaisePropertyChanged("TotalCount");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TimeSheet", Namespace="http://schemas.datacontract.org/2004/07/WcfServices")]
    [System.SerializableAttribute()]
    public partial class TimeSheet : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal AdjustmentInMinutesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AllowSuperVisorModifyWorkTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApprovedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CandidateGuidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CandidateIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CandidateWorkTimeStatusIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> ClockInField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> ClockOutField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ClockTimeInHoursField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CompanyLocationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContactNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> CreatedOnUtcField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartmentNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmployeeFirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmployeeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmployeeLastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FranchiseIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsCurrentWeekField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime JobEndDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal JobOrderDurationInHoursField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JobOrderGuidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int JobOrderIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JobShiftField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime JobStartDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JobTitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocationNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal NetWorkTimeInHoursField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal NetWorkTimeInMinutesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NoteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OtherAlertsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OvertimeMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Payroll_BatchIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TimeSheetIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> UpdatedOnUtcField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VendorNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int WeekOfYearField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int YearField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal AdjustmentInMinutes {
            get {
                return this.AdjustmentInMinutesField;
            }
            set {
                if ((this.AdjustmentInMinutesField.Equals(value) != true)) {
                    this.AdjustmentInMinutesField = value;
                    this.RaisePropertyChanged("AdjustmentInMinutes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool AllowSuperVisorModifyWorkTime {
            get {
                return this.AllowSuperVisorModifyWorkTimeField;
            }
            set {
                if ((this.AllowSuperVisorModifyWorkTimeField.Equals(value) != true)) {
                    this.AllowSuperVisorModifyWorkTimeField = value;
                    this.RaisePropertyChanged("AllowSuperVisorModifyWorkTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApprovedBy {
            get {
                return this.ApprovedByField;
            }
            set {
                if ((object.ReferenceEquals(this.ApprovedByField, value) != true)) {
                    this.ApprovedByField = value;
                    this.RaisePropertyChanged("ApprovedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CandidateGuid {
            get {
                return this.CandidateGuidField;
            }
            set {
                if ((object.ReferenceEquals(this.CandidateGuidField, value) != true)) {
                    this.CandidateGuidField = value;
                    this.RaisePropertyChanged("CandidateGuid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CandidateId {
            get {
                return this.CandidateIdField;
            }
            set {
                if ((this.CandidateIdField.Equals(value) != true)) {
                    this.CandidateIdField = value;
                    this.RaisePropertyChanged("CandidateId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CandidateWorkTimeStatusId {
            get {
                return this.CandidateWorkTimeStatusIdField;
            }
            set {
                if ((this.CandidateWorkTimeStatusIdField.Equals(value) != true)) {
                    this.CandidateWorkTimeStatusIdField = value;
                    this.RaisePropertyChanged("CandidateWorkTimeStatusId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ClockIn {
            get {
                return this.ClockInField;
            }
            set {
                if ((this.ClockInField.Equals(value) != true)) {
                    this.ClockInField = value;
                    this.RaisePropertyChanged("ClockIn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ClockOut {
            get {
                return this.ClockOutField;
            }
            set {
                if ((this.ClockOutField.Equals(value) != true)) {
                    this.ClockOutField = value;
                    this.RaisePropertyChanged("ClockOut");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ClockTimeInHours {
            get {
                return this.ClockTimeInHoursField;
            }
            set {
                if ((this.ClockTimeInHoursField.Equals(value) != true)) {
                    this.ClockTimeInHoursField = value;
                    this.RaisePropertyChanged("ClockTimeInHours");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CompanyLocationId {
            get {
                return this.CompanyLocationIdField;
            }
            set {
                if ((this.CompanyLocationIdField.Equals(value) != true)) {
                    this.CompanyLocationIdField = value;
                    this.RaisePropertyChanged("CompanyLocationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CompanyName {
            get {
                return this.CompanyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyNameField, value) != true)) {
                    this.CompanyNameField = value;
                    this.RaisePropertyChanged("CompanyName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContactName {
            get {
                return this.ContactNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactNameField, value) != true)) {
                    this.ContactNameField = value;
                    this.RaisePropertyChanged("ContactName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CreatedOnUtc {
            get {
                return this.CreatedOnUtcField;
            }
            set {
                if ((this.CreatedOnUtcField.Equals(value) != true)) {
                    this.CreatedOnUtcField = value;
                    this.RaisePropertyChanged("CreatedOnUtc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DepartmentName {
            get {
                return this.DepartmentNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartmentNameField, value) != true)) {
                    this.DepartmentNameField = value;
                    this.RaisePropertyChanged("DepartmentName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmployeeFirstName {
            get {
                return this.EmployeeFirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployeeFirstNameField, value) != true)) {
                    this.EmployeeFirstNameField = value;
                    this.RaisePropertyChanged("EmployeeFirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmployeeId {
            get {
                return this.EmployeeIdField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployeeIdField, value) != true)) {
                    this.EmployeeIdField = value;
                    this.RaisePropertyChanged("EmployeeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmployeeLastName {
            get {
                return this.EmployeeLastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployeeLastNameField, value) != true)) {
                    this.EmployeeLastNameField = value;
                    this.RaisePropertyChanged("EmployeeLastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FranchiseId {
            get {
                return this.FranchiseIdField;
            }
            set {
                if ((this.FranchiseIdField.Equals(value) != true)) {
                    this.FranchiseIdField = value;
                    this.RaisePropertyChanged("FranchiseId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsCurrentWeek {
            get {
                return this.IsCurrentWeekField;
            }
            set {
                if ((this.IsCurrentWeekField.Equals(value) != true)) {
                    this.IsCurrentWeekField = value;
                    this.RaisePropertyChanged("IsCurrentWeek");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime JobEndDateTime {
            get {
                return this.JobEndDateTimeField;
            }
            set {
                if ((this.JobEndDateTimeField.Equals(value) != true)) {
                    this.JobEndDateTimeField = value;
                    this.RaisePropertyChanged("JobEndDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal JobOrderDurationInHours {
            get {
                return this.JobOrderDurationInHoursField;
            }
            set {
                if ((this.JobOrderDurationInHoursField.Equals(value) != true)) {
                    this.JobOrderDurationInHoursField = value;
                    this.RaisePropertyChanged("JobOrderDurationInHours");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string JobOrderGuid {
            get {
                return this.JobOrderGuidField;
            }
            set {
                if ((object.ReferenceEquals(this.JobOrderGuidField, value) != true)) {
                    this.JobOrderGuidField = value;
                    this.RaisePropertyChanged("JobOrderGuid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int JobOrderId {
            get {
                return this.JobOrderIdField;
            }
            set {
                if ((this.JobOrderIdField.Equals(value) != true)) {
                    this.JobOrderIdField = value;
                    this.RaisePropertyChanged("JobOrderId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string JobShift {
            get {
                return this.JobShiftField;
            }
            set {
                if ((object.ReferenceEquals(this.JobShiftField, value) != true)) {
                    this.JobShiftField = value;
                    this.RaisePropertyChanged("JobShift");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime JobStartDateTime {
            get {
                return this.JobStartDateTimeField;
            }
            set {
                if ((this.JobStartDateTimeField.Equals(value) != true)) {
                    this.JobStartDateTimeField = value;
                    this.RaisePropertyChanged("JobStartDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string JobTitle {
            get {
                return this.JobTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.JobTitleField, value) != true)) {
                    this.JobTitleField = value;
                    this.RaisePropertyChanged("JobTitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LocationName {
            get {
                return this.LocationNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LocationNameField, value) != true)) {
                    this.LocationNameField = value;
                    this.RaisePropertyChanged("LocationName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal NetWorkTimeInHours {
            get {
                return this.NetWorkTimeInHoursField;
            }
            set {
                if ((this.NetWorkTimeInHoursField.Equals(value) != true)) {
                    this.NetWorkTimeInHoursField = value;
                    this.RaisePropertyChanged("NetWorkTimeInHours");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal NetWorkTimeInMinutes {
            get {
                return this.NetWorkTimeInMinutesField;
            }
            set {
                if ((this.NetWorkTimeInMinutesField.Equals(value) != true)) {
                    this.NetWorkTimeInMinutesField = value;
                    this.RaisePropertyChanged("NetWorkTimeInMinutes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Note {
            get {
                return this.NoteField;
            }
            set {
                if ((object.ReferenceEquals(this.NoteField, value) != true)) {
                    this.NoteField = value;
                    this.RaisePropertyChanged("Note");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OtherAlerts {
            get {
                return this.OtherAlertsField;
            }
            set {
                if ((object.ReferenceEquals(this.OtherAlertsField, value) != true)) {
                    this.OtherAlertsField = value;
                    this.RaisePropertyChanged("OtherAlerts");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OvertimeMessage {
            get {
                return this.OvertimeMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.OvertimeMessageField, value) != true)) {
                    this.OvertimeMessageField = value;
                    this.RaisePropertyChanged("OvertimeMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Payroll_BatchId {
            get {
                return this.Payroll_BatchIdField;
            }
            set {
                if ((this.Payroll_BatchIdField.Equals(value) != true)) {
                    this.Payroll_BatchIdField = value;
                    this.RaisePropertyChanged("Payroll_BatchId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TimeSheetId {
            get {
                return this.TimeSheetIdField;
            }
            set {
                if ((this.TimeSheetIdField.Equals(value) != true)) {
                    this.TimeSheetIdField = value;
                    this.RaisePropertyChanged("TimeSheetId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> UpdatedOnUtc {
            get {
                return this.UpdatedOnUtcField;
            }
            set {
                if ((this.UpdatedOnUtcField.Equals(value) != true)) {
                    this.UpdatedOnUtcField = value;
                    this.RaisePropertyChanged("UpdatedOnUtc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VendorName {
            get {
                return this.VendorNameField;
            }
            set {
                if ((object.ReferenceEquals(this.VendorNameField, value) != true)) {
                    this.VendorNameField = value;
                    this.RaisePropertyChanged("VendorName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int WeekOfYear {
            get {
                return this.WeekOfYearField;
            }
            set {
                if ((this.WeekOfYearField.Equals(value) != true)) {
                    this.WeekOfYearField = value;
                    this.RaisePropertyChanged("WeekOfYear");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Year {
            get {
                return this.YearField;
            }
            set {
                if ((this.YearField.Equals(value) != true)) {
                    this.YearField = value;
                    this.RaisePropertyChanged("Year");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PagedListResultOfSimpleEmployeeTimeChartHistorymfZTS4bC", Namespace="http://schemas.datacontract.org/2004/07/WcfServices")]
    [System.SerializableAttribute()]
    public partial class PagedListResultOfSimpleEmployeeTimeChartHistorymfZTS4bC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Wfm.Admin.ClientServiceReference.SimpleEmployeeTimeChartHistory[] ItemsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long TotalCountField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Wfm.Admin.ClientServiceReference.SimpleEmployeeTimeChartHistory[] Items {
            get {
                return this.ItemsField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemsField, value) != true)) {
                    this.ItemsField = value;
                    this.RaisePropertyChanged("Items");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long TotalCount {
            get {
                return this.TotalCountField;
            }
            set {
                if ((this.TotalCountField.Equals(value) != true)) {
                    this.TotalCountField = value;
                    this.RaisePropertyChanged("TotalCount");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SimpleEmployeeTimeChartHistory", Namespace="http://schemas.datacontract.org/2004/07/WcfServices.TimeSheets")]
    [System.SerializableAttribute()]
    public partial class SimpleEmployeeTimeChartHistory : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApprovedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CompanyContactIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CompanyDepartmentIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CompanyIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CompanyLocationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContactNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartmentNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmployeeFirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EmployeeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmployeeLastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmployeeNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FranchiseIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FranchiseNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal FridayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FridayDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int JobOrderIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JobTitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocationNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal MondayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime MondayDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> OTHoursField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> RegularHoursField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal SaturdayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime SaturdayDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> SubTotalHoursField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal SundayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime SundayDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ThursdayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ThursdayDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TuesdayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TuesdayDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal WednesdayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime WednesdayDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int WeekOfYearField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int YearField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApprovedBy {
            get {
                return this.ApprovedByField;
            }
            set {
                if ((object.ReferenceEquals(this.ApprovedByField, value) != true)) {
                    this.ApprovedByField = value;
                    this.RaisePropertyChanged("ApprovedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CompanyContactId {
            get {
                return this.CompanyContactIdField;
            }
            set {
                if ((this.CompanyContactIdField.Equals(value) != true)) {
                    this.CompanyContactIdField = value;
                    this.RaisePropertyChanged("CompanyContactId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CompanyDepartmentId {
            get {
                return this.CompanyDepartmentIdField;
            }
            set {
                if ((this.CompanyDepartmentIdField.Equals(value) != true)) {
                    this.CompanyDepartmentIdField = value;
                    this.RaisePropertyChanged("CompanyDepartmentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CompanyId {
            get {
                return this.CompanyIdField;
            }
            set {
                if ((this.CompanyIdField.Equals(value) != true)) {
                    this.CompanyIdField = value;
                    this.RaisePropertyChanged("CompanyId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CompanyLocationId {
            get {
                return this.CompanyLocationIdField;
            }
            set {
                if ((this.CompanyLocationIdField.Equals(value) != true)) {
                    this.CompanyLocationIdField = value;
                    this.RaisePropertyChanged("CompanyLocationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CompanyName {
            get {
                return this.CompanyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyNameField, value) != true)) {
                    this.CompanyNameField = value;
                    this.RaisePropertyChanged("CompanyName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContactName {
            get {
                return this.ContactNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactNameField, value) != true)) {
                    this.ContactNameField = value;
                    this.RaisePropertyChanged("ContactName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DepartmentName {
            get {
                return this.DepartmentNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartmentNameField, value) != true)) {
                    this.DepartmentNameField = value;
                    this.RaisePropertyChanged("DepartmentName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmployeeFirstName {
            get {
                return this.EmployeeFirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployeeFirstNameField, value) != true)) {
                    this.EmployeeFirstNameField = value;
                    this.RaisePropertyChanged("EmployeeFirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EmployeeId {
            get {
                return this.EmployeeIdField;
            }
            set {
                if ((this.EmployeeIdField.Equals(value) != true)) {
                    this.EmployeeIdField = value;
                    this.RaisePropertyChanged("EmployeeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmployeeLastName {
            get {
                return this.EmployeeLastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployeeLastNameField, value) != true)) {
                    this.EmployeeLastNameField = value;
                    this.RaisePropertyChanged("EmployeeLastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmployeeNumber {
            get {
                return this.EmployeeNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployeeNumberField, value) != true)) {
                    this.EmployeeNumberField = value;
                    this.RaisePropertyChanged("EmployeeNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FranchiseId {
            get {
                return this.FranchiseIdField;
            }
            set {
                if ((this.FranchiseIdField.Equals(value) != true)) {
                    this.FranchiseIdField = value;
                    this.RaisePropertyChanged("FranchiseId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FranchiseName {
            get {
                return this.FranchiseNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FranchiseNameField, value) != true)) {
                    this.FranchiseNameField = value;
                    this.RaisePropertyChanged("FranchiseName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Friday {
            get {
                return this.FridayField;
            }
            set {
                if ((this.FridayField.Equals(value) != true)) {
                    this.FridayField = value;
                    this.RaisePropertyChanged("Friday");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FridayDate {
            get {
                return this.FridayDateField;
            }
            set {
                if ((this.FridayDateField.Equals(value) != true)) {
                    this.FridayDateField = value;
                    this.RaisePropertyChanged("FridayDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int JobOrderId {
            get {
                return this.JobOrderIdField;
            }
            set {
                if ((this.JobOrderIdField.Equals(value) != true)) {
                    this.JobOrderIdField = value;
                    this.RaisePropertyChanged("JobOrderId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string JobTitle {
            get {
                return this.JobTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.JobTitleField, value) != true)) {
                    this.JobTitleField = value;
                    this.RaisePropertyChanged("JobTitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LocationName {
            get {
                return this.LocationNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LocationNameField, value) != true)) {
                    this.LocationNameField = value;
                    this.RaisePropertyChanged("LocationName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Monday {
            get {
                return this.MondayField;
            }
            set {
                if ((this.MondayField.Equals(value) != true)) {
                    this.MondayField = value;
                    this.RaisePropertyChanged("Monday");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime MondayDate {
            get {
                return this.MondayDateField;
            }
            set {
                if ((this.MondayDateField.Equals(value) != true)) {
                    this.MondayDateField = value;
                    this.RaisePropertyChanged("MondayDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> OTHours {
            get {
                return this.OTHoursField;
            }
            set {
                if ((this.OTHoursField.Equals(value) != true)) {
                    this.OTHoursField = value;
                    this.RaisePropertyChanged("OTHours");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> RegularHours {
            get {
                return this.RegularHoursField;
            }
            set {
                if ((this.RegularHoursField.Equals(value) != true)) {
                    this.RegularHoursField = value;
                    this.RaisePropertyChanged("RegularHours");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Saturday {
            get {
                return this.SaturdayField;
            }
            set {
                if ((this.SaturdayField.Equals(value) != true)) {
                    this.SaturdayField = value;
                    this.RaisePropertyChanged("Saturday");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime SaturdayDate {
            get {
                return this.SaturdayDateField;
            }
            set {
                if ((this.SaturdayDateField.Equals(value) != true)) {
                    this.SaturdayDateField = value;
                    this.RaisePropertyChanged("SaturdayDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> SubTotalHours {
            get {
                return this.SubTotalHoursField;
            }
            set {
                if ((this.SubTotalHoursField.Equals(value) != true)) {
                    this.SubTotalHoursField = value;
                    this.RaisePropertyChanged("SubTotalHours");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Sunday {
            get {
                return this.SundayField;
            }
            set {
                if ((this.SundayField.Equals(value) != true)) {
                    this.SundayField = value;
                    this.RaisePropertyChanged("Sunday");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime SundayDate {
            get {
                return this.SundayDateField;
            }
            set {
                if ((this.SundayDateField.Equals(value) != true)) {
                    this.SundayDateField = value;
                    this.RaisePropertyChanged("SundayDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Thursday {
            get {
                return this.ThursdayField;
            }
            set {
                if ((this.ThursdayField.Equals(value) != true)) {
                    this.ThursdayField = value;
                    this.RaisePropertyChanged("Thursday");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ThursdayDate {
            get {
                return this.ThursdayDateField;
            }
            set {
                if ((this.ThursdayDateField.Equals(value) != true)) {
                    this.ThursdayDateField = value;
                    this.RaisePropertyChanged("ThursdayDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Tuesday {
            get {
                return this.TuesdayField;
            }
            set {
                if ((this.TuesdayField.Equals(value) != true)) {
                    this.TuesdayField = value;
                    this.RaisePropertyChanged("Tuesday");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime TuesdayDate {
            get {
                return this.TuesdayDateField;
            }
            set {
                if ((this.TuesdayDateField.Equals(value) != true)) {
                    this.TuesdayDateField = value;
                    this.RaisePropertyChanged("TuesdayDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Wednesday {
            get {
                return this.WednesdayField;
            }
            set {
                if ((this.WednesdayField.Equals(value) != true)) {
                    this.WednesdayField = value;
                    this.RaisePropertyChanged("Wednesday");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime WednesdayDate {
            get {
                return this.WednesdayDateField;
            }
            set {
                if ((this.WednesdayDateField.Equals(value) != true)) {
                    this.WednesdayDateField = value;
                    this.RaisePropertyChanged("WednesdayDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int WeekOfYear {
            get {
                return this.WeekOfYearField;
            }
            set {
                if ((this.WeekOfYearField.Equals(value) != true)) {
                    this.WeekOfYearField = value;
                    this.RaisePropertyChanged("WeekOfYear");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Year {
            get {
                return this.YearField;
            }
            set {
                if ((this.YearField.Equals(value) != true)) {
                    this.YearField = value;
                    this.RaisePropertyChanged("Year");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TimeSheetOperationResult", Namespace="http://schemas.datacontract.org/2004/07/WcfServices")]
    [System.SerializableAttribute()]
    public partial class TimeSheetOperationResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Wfm.Admin.ClientServiceReference.BasicResult ResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Wfm.Admin.ClientServiceReference.TimeSheet TimeSheetField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Wfm.Admin.ClientServiceReference.BasicResult Result {
            get {
                return this.ResultField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultField, value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Wfm.Admin.ClientServiceReference.TimeSheet TimeSheet {
            get {
                return this.TimeSheetField;
            }
            set {
                if ((object.ReferenceEquals(this.TimeSheetField, value) != true)) {
                    this.TimeSheetField = value;
                    this.RaisePropertyChanged("TimeSheet");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BasicResult", Namespace="http://schemas.datacontract.org/2004/07/WcfServices")]
    [System.SerializableAttribute()]
    public partial class BasicResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SuccessField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success {
            get {
                return this.SuccessField;
            }
            set {
                if ((this.SuccessField.Equals(value) != true)) {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TimeSheetAndSession", Namespace="http://schemas.datacontract.org/2004/07/WcfServices")]
    [System.SerializableAttribute()]
    public partial class TimeSheetAndSession : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Wfm.Admin.ClientServiceReference.TimeSheetSlim CandidateTimeSheetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SessionIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Wfm.Admin.ClientServiceReference.TimeSheetSlim CandidateTimeSheet {
            get {
                return this.CandidateTimeSheetField;
            }
            set {
                if ((object.ReferenceEquals(this.CandidateTimeSheetField, value) != true)) {
                    this.CandidateTimeSheetField = value;
                    this.RaisePropertyChanged("CandidateTimeSheet");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SessionId {
            get {
                return this.SessionIdField;
            }
            set {
                if ((object.ReferenceEquals(this.SessionIdField, value) != true)) {
                    this.SessionIdField = value;
                    this.RaisePropertyChanged("SessionId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TimeSheetSlim", Namespace="http://schemas.datacontract.org/2004/07/WcfServices")]
    [System.SerializableAttribute()]
    public partial class TimeSheetSlim : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CandidateGuidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NoteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TimeSheetIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CandidateGuid {
            get {
                return this.CandidateGuidField;
            }
            set {
                if ((object.ReferenceEquals(this.CandidateGuidField, value) != true)) {
                    this.CandidateGuidField = value;
                    this.RaisePropertyChanged("CandidateGuid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Note {
            get {
                return this.NoteField;
            }
            set {
                if ((object.ReferenceEquals(this.NoteField, value) != true)) {
                    this.NoteField = value;
                    this.RaisePropertyChanged("Note");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TimeSheetId {
            get {
                return this.TimeSheetIdField;
            }
            set {
                if ((this.TimeSheetIdField.Equals(value) != true)) {
                    this.TimeSheetIdField = value;
                    this.RaisePropertyChanged("TimeSheetId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WorkTime", Namespace="http://schemas.datacontract.org/2004/07/WcfServices")]
    [System.SerializableAttribute()]
    public partial class WorkTime : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CandidateGuidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JobOrderGuidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal NetWorkTimeInHoursField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NoteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime WorkDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CandidateGuid {
            get {
                return this.CandidateGuidField;
            }
            set {
                if ((object.ReferenceEquals(this.CandidateGuidField, value) != true)) {
                    this.CandidateGuidField = value;
                    this.RaisePropertyChanged("CandidateGuid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string JobOrderGuid {
            get {
                return this.JobOrderGuidField;
            }
            set {
                if ((object.ReferenceEquals(this.JobOrderGuidField, value) != true)) {
                    this.JobOrderGuidField = value;
                    this.RaisePropertyChanged("JobOrderGuid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal NetWorkTimeInHours {
            get {
                return this.NetWorkTimeInHoursField;
            }
            set {
                if ((this.NetWorkTimeInHoursField.Equals(value) != true)) {
                    this.NetWorkTimeInHoursField = value;
                    this.RaisePropertyChanged("NetWorkTimeInHours");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Note {
            get {
                return this.NoteField;
            }
            set {
                if ((object.ReferenceEquals(this.NoteField, value) != true)) {
                    this.NoteField = value;
                    this.RaisePropertyChanged("Note");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime WorkDate {
            get {
                return this.WorkDateField;
            }
            set {
                if ((this.WorkDateField.Equals(value) != true)) {
                    this.WorkDateField = value;
                    this.RaisePropertyChanged("WorkDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ClientServiceReference.IWfmService")]
    public interface IWfmService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWfmService/PingWfmService", ReplyAction="http://tempuri.org/IWfmService/PingWfmServiceResponse")]
        string PingWfmService();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWfmService/PingWfmService", ReplyAction="http://tempuri.org/IWfmService/PingWfmServiceResponse")]
        System.Threading.Tasks.Task<string> PingWfmServiceAsync();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IWfmService/SendMassEmail")]
        void SendMassEmail(string User, string Password, string SentBy, int FranchiseId, string SelectedIds, string targetType, string From, string FromName, string Subject, string Message, int MessageCategoryId);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IWfmService/SendMassEmail")]
        System.Threading.Tasks.Task SendMassEmailAsync(string User, string Password, string SentBy, int FranchiseId, string SelectedIds, string targetType, string From, string FromName, string Subject, string Message, int MessageCategoryId);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IWfmService/SendMassMessage")]
        void SendMassMessage(string User, string Password, string SelectedIds, string Body, string From);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IWfmService/SendMassMessage")]
        System.Threading.Tasks.Task SendMassMessageAsync(string User, string Password, string SelectedIds, string Body, string From);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWfmService/AuthenticateUser", ReplyAction="http://tempuri.org/IWfmService/AuthenticateUserResponse")]
        Wfm.Admin.ClientServiceReference.AuthenticationResult AuthenticateUser(string accountUsername, string accountPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWfmService/AuthenticateUser", ReplyAction="http://tempuri.org/IWfmService/AuthenticateUserResponse")]
        System.Threading.Tasks.Task<Wfm.Admin.ClientServiceReference.AuthenticationResult> AuthenticateUserAsync(string accountUsername, string accountPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWfmService/RefreshSession", ReplyAction="http://tempuri.org/IWfmService/RefreshSessionResponse")]
        Wfm.Admin.ClientServiceReference.AuthenticationResult RefreshSession(string userName, string sessionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWfmService/RefreshSession", ReplyAction="http://tempuri.org/IWfmService/RefreshSessionResponse")]
        System.Threading.Tasks.Task<Wfm.Admin.ClientServiceReference.AuthenticationResult> RefreshSessionAsync(string userName, string sessionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWfmService/LogOut", ReplyAction="http://tempuri.org/IWfmService/LogOutResponse")]
        void LogOut(string sessionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWfmService/LogOut", ReplyAction="http://tempuri.org/IWfmService/LogOutResponse")]
        System.Threading.Tasks.Task LogOutAsync(string sessionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWfmService/SendPasswordResetMessage", ReplyAction="http://tempuri.org/IWfmService/SendPasswordResetMessageResponse")]
        bool SendPasswordResetMessage(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWfmService/SendPasswordResetMessage", ReplyAction="http://tempuri.org/IWfmService/SendPasswordResetMessageResponse")]
        System.Threading.Tasks.Task<bool> SendPasswordResetMessageAsync(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWfmService/GetDailyTimeSheet", ReplyAction="http://tempuri.org/IWfmService/GetDailyTimeSheetResponse")]
        Wfm.Admin.ClientServiceReference.PagedListResultOfTimeSheetHpUzpNkN GetDailyTimeSheet(string SessionId, bool submittedOnly, int pageSize, int pageIndex, string sortBy, string sortOrder, string filterBy, string filterCondition, string filterValue);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWfmService/GetDailyTimeSheet", ReplyAction="http://tempuri.org/IWfmService/GetDailyTimeSheetResponse")]
        System.Threading.Tasks.Task<Wfm.Admin.ClientServiceReference.PagedListResultOfTimeSheetHpUzpNkN> GetDailyTimeSheetAsync(string SessionId, bool submittedOnly, int pageSize, int pageIndex, string sortBy, string sortOrder, string filterBy, string filterCondition, string filterValue);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWfmService/GetEmployeeTimeSheetHistoryByDate", ReplyAction="http://tempuri.org/IWfmService/GetEmployeeTimeSheetHistoryByDateResponse")]
        Wfm.Admin.ClientServiceReference.PagedListResultOfSimpleEmployeeTimeChartHistorymfZTS4bC GetEmployeeTimeSheetHistoryByDate(string sessionId, System.DateTime start, System.DateTime end, int pageSize, int pageIndex, string sortBy, string sortOrder, string filterBy, string filterCondition, string filterValue);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWfmService/GetEmployeeTimeSheetHistoryByDate", ReplyAction="http://tempuri.org/IWfmService/GetEmployeeTimeSheetHistoryByDateResponse")]
        System.Threading.Tasks.Task<Wfm.Admin.ClientServiceReference.PagedListResultOfSimpleEmployeeTimeChartHistorymfZTS4bC> GetEmployeeTimeSheetHistoryByDateAsync(string sessionId, System.DateTime start, System.DateTime end, int pageSize, int pageIndex, string sortBy, string sortOrder, string filterBy, string filterCondition, string filterValue);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWfmService/GetTimeSheetForApproval", ReplyAction="http://tempuri.org/IWfmService/GetTimeSheetForApprovalResponse")]
        Wfm.Admin.ClientServiceReference.PagedListResultOfTimeSheetHpUzpNkN GetTimeSheetForApproval(string SessionId, System.DateTime weekStartDate, bool submittedOnly, int pageSize, int pageIndex, string sortBy, string sortOrder, string filterBy, string filterCondition, string filterValue);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWfmService/GetTimeSheetForApproval", ReplyAction="http://tempuri.org/IWfmService/GetTimeSheetForApprovalResponse")]
        System.Threading.Tasks.Task<Wfm.Admin.ClientServiceReference.PagedListResultOfTimeSheetHpUzpNkN> GetTimeSheetForApprovalAsync(string SessionId, System.DateTime weekStartDate, bool submittedOnly, int pageSize, int pageIndex, string sortBy, string sortOrder, string filterBy, string filterCondition, string filterValue);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWfmService/UpdateTimeSheet", ReplyAction="http://tempuri.org/IWfmService/UpdateTimeSheetResponse")]
        Wfm.Admin.ClientServiceReference.TimeSheetOperationResult UpdateTimeSheet(string SessionId, Wfm.Admin.ClientServiceReference.TimeSheet candidateTimeSheet);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWfmService/UpdateTimeSheet", ReplyAction="http://tempuri.org/IWfmService/UpdateTimeSheetResponse")]
        System.Threading.Tasks.Task<Wfm.Admin.ClientServiceReference.TimeSheetOperationResult> UpdateTimeSheetAsync(string SessionId, Wfm.Admin.ClientServiceReference.TimeSheet candidateTimeSheet);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWfmService/ApproveTimeSheet", ReplyAction="http://tempuri.org/IWfmService/ApproveTimeSheetResponse")]
        Wfm.Admin.ClientServiceReference.TimeSheetOperationResult ApproveTimeSheet(Wfm.Admin.ClientServiceReference.TimeSheetAndSession input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWfmService/ApproveTimeSheet", ReplyAction="http://tempuri.org/IWfmService/ApproveTimeSheetResponse")]
        System.Threading.Tasks.Task<Wfm.Admin.ClientServiceReference.TimeSheetOperationResult> ApproveTimeSheetAsync(Wfm.Admin.ClientServiceReference.TimeSheetAndSession input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWfmService/ApproveTimeSheets", ReplyAction="http://tempuri.org/IWfmService/ApproveTimeSheetsResponse")]
        Wfm.Admin.ClientServiceReference.PagedListResultOfTimeSheetHpUzpNkN ApproveTimeSheets(string sessionId, Wfm.Admin.ClientServiceReference.TimeSheetSlim[] timeSheets);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWfmService/ApproveTimeSheets", ReplyAction="http://tempuri.org/IWfmService/ApproveTimeSheetsResponse")]
        System.Threading.Tasks.Task<Wfm.Admin.ClientServiceReference.PagedListResultOfTimeSheetHpUzpNkN> ApproveTimeSheetsAsync(string sessionId, Wfm.Admin.ClientServiceReference.TimeSheetSlim[] timeSheets);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWfmService/RejectTimeSheet", ReplyAction="http://tempuri.org/IWfmService/RejectTimeSheetResponse")]
        Wfm.Admin.ClientServiceReference.TimeSheetOperationResult RejectTimeSheet(Wfm.Admin.ClientServiceReference.TimeSheetAndSession input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWfmService/RejectTimeSheet", ReplyAction="http://tempuri.org/IWfmService/RejectTimeSheetResponse")]
        System.Threading.Tasks.Task<Wfm.Admin.ClientServiceReference.TimeSheetOperationResult> RejectTimeSheetAsync(Wfm.Admin.ClientServiceReference.TimeSheetAndSession input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWfmService/AddCandidateWorkTime", ReplyAction="http://tempuri.org/IWfmService/AddCandidateWorkTimeResponse")]
        Wfm.Admin.ClientServiceReference.TimeSheetOperationResult AddCandidateWorkTime(string sessionId, Wfm.Admin.ClientServiceReference.WorkTime workTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWfmService/AddCandidateWorkTime", ReplyAction="http://tempuri.org/IWfmService/AddCandidateWorkTimeResponse")]
        System.Threading.Tasks.Task<Wfm.Admin.ClientServiceReference.TimeSheetOperationResult> AddCandidateWorkTimeAsync(string sessionId, Wfm.Admin.ClientServiceReference.WorkTime workTime);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWfmServiceChannel : Wfm.Admin.ClientServiceReference.IWfmService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WfmServiceClient : System.ServiceModel.ClientBase<Wfm.Admin.ClientServiceReference.IWfmService>, Wfm.Admin.ClientServiceReference.IWfmService {
        
        public WfmServiceClient() {
        }
        
        public WfmServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WfmServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WfmServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WfmServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string PingWfmService() {
            return base.Channel.PingWfmService();
        }
        
        public System.Threading.Tasks.Task<string> PingWfmServiceAsync() {
            return base.Channel.PingWfmServiceAsync();
        }
        
        public void SendMassEmail(string User, string Password, string SentBy, int FranchiseId, string SelectedIds, string targetType, string From, string FromName, string Subject, string Message, int MessageCategoryId) {
            base.Channel.SendMassEmail(User, Password, SentBy, FranchiseId, SelectedIds, targetType, From, FromName, Subject, Message, MessageCategoryId);
        }
        
        public System.Threading.Tasks.Task SendMassEmailAsync(string User, string Password, string SentBy, int FranchiseId, string SelectedIds, string targetType, string From, string FromName, string Subject, string Message, int MessageCategoryId) {
            return base.Channel.SendMassEmailAsync(User, Password, SentBy, FranchiseId, SelectedIds, targetType, From, FromName, Subject, Message, MessageCategoryId);
        }
        
        public void SendMassMessage(string User, string Password, string SelectedIds, string Body, string From) {
            base.Channel.SendMassMessage(User, Password, SelectedIds, Body, From);
        }
        
        public System.Threading.Tasks.Task SendMassMessageAsync(string User, string Password, string SelectedIds, string Body, string From) {
            return base.Channel.SendMassMessageAsync(User, Password, SelectedIds, Body, From);
        }
        
        public Wfm.Admin.ClientServiceReference.AuthenticationResult AuthenticateUser(string accountUsername, string accountPassword) {
            return base.Channel.AuthenticateUser(accountUsername, accountPassword);
        }
        
        public System.Threading.Tasks.Task<Wfm.Admin.ClientServiceReference.AuthenticationResult> AuthenticateUserAsync(string accountUsername, string accountPassword) {
            return base.Channel.AuthenticateUserAsync(accountUsername, accountPassword);
        }
        
        public Wfm.Admin.ClientServiceReference.AuthenticationResult RefreshSession(string userName, string sessionId) {
            return base.Channel.RefreshSession(userName, sessionId);
        }
        
        public System.Threading.Tasks.Task<Wfm.Admin.ClientServiceReference.AuthenticationResult> RefreshSessionAsync(string userName, string sessionId) {
            return base.Channel.RefreshSessionAsync(userName, sessionId);
        }
        
        public void LogOut(string sessionId) {
            base.Channel.LogOut(sessionId);
        }
        
        public System.Threading.Tasks.Task LogOutAsync(string sessionId) {
            return base.Channel.LogOutAsync(sessionId);
        }
        
        public bool SendPasswordResetMessage(string email) {
            return base.Channel.SendPasswordResetMessage(email);
        }
        
        public System.Threading.Tasks.Task<bool> SendPasswordResetMessageAsync(string email) {
            return base.Channel.SendPasswordResetMessageAsync(email);
        }
        
        public Wfm.Admin.ClientServiceReference.PagedListResultOfTimeSheetHpUzpNkN GetDailyTimeSheet(string SessionId, bool submittedOnly, int pageSize, int pageIndex, string sortBy, string sortOrder, string filterBy, string filterCondition, string filterValue) {
            return base.Channel.GetDailyTimeSheet(SessionId, submittedOnly, pageSize, pageIndex, sortBy, sortOrder, filterBy, filterCondition, filterValue);
        }
        
        public System.Threading.Tasks.Task<Wfm.Admin.ClientServiceReference.PagedListResultOfTimeSheetHpUzpNkN> GetDailyTimeSheetAsync(string SessionId, bool submittedOnly, int pageSize, int pageIndex, string sortBy, string sortOrder, string filterBy, string filterCondition, string filterValue) {
            return base.Channel.GetDailyTimeSheetAsync(SessionId, submittedOnly, pageSize, pageIndex, sortBy, sortOrder, filterBy, filterCondition, filterValue);
        }
        
        public Wfm.Admin.ClientServiceReference.PagedListResultOfSimpleEmployeeTimeChartHistorymfZTS4bC GetEmployeeTimeSheetHistoryByDate(string sessionId, System.DateTime start, System.DateTime end, int pageSize, int pageIndex, string sortBy, string sortOrder, string filterBy, string filterCondition, string filterValue) {
            return base.Channel.GetEmployeeTimeSheetHistoryByDate(sessionId, start, end, pageSize, pageIndex, sortBy, sortOrder, filterBy, filterCondition, filterValue);
        }
        
        public System.Threading.Tasks.Task<Wfm.Admin.ClientServiceReference.PagedListResultOfSimpleEmployeeTimeChartHistorymfZTS4bC> GetEmployeeTimeSheetHistoryByDateAsync(string sessionId, System.DateTime start, System.DateTime end, int pageSize, int pageIndex, string sortBy, string sortOrder, string filterBy, string filterCondition, string filterValue) {
            return base.Channel.GetEmployeeTimeSheetHistoryByDateAsync(sessionId, start, end, pageSize, pageIndex, sortBy, sortOrder, filterBy, filterCondition, filterValue);
        }
        
        public Wfm.Admin.ClientServiceReference.PagedListResultOfTimeSheetHpUzpNkN GetTimeSheetForApproval(string SessionId, System.DateTime weekStartDate, bool submittedOnly, int pageSize, int pageIndex, string sortBy, string sortOrder, string filterBy, string filterCondition, string filterValue) {
            return base.Channel.GetTimeSheetForApproval(SessionId, weekStartDate, submittedOnly, pageSize, pageIndex, sortBy, sortOrder, filterBy, filterCondition, filterValue);
        }
        
        public System.Threading.Tasks.Task<Wfm.Admin.ClientServiceReference.PagedListResultOfTimeSheetHpUzpNkN> GetTimeSheetForApprovalAsync(string SessionId, System.DateTime weekStartDate, bool submittedOnly, int pageSize, int pageIndex, string sortBy, string sortOrder, string filterBy, string filterCondition, string filterValue) {
            return base.Channel.GetTimeSheetForApprovalAsync(SessionId, weekStartDate, submittedOnly, pageSize, pageIndex, sortBy, sortOrder, filterBy, filterCondition, filterValue);
        }
        
        public Wfm.Admin.ClientServiceReference.TimeSheetOperationResult UpdateTimeSheet(string SessionId, Wfm.Admin.ClientServiceReference.TimeSheet candidateTimeSheet) {
            return base.Channel.UpdateTimeSheet(SessionId, candidateTimeSheet);
        }
        
        public System.Threading.Tasks.Task<Wfm.Admin.ClientServiceReference.TimeSheetOperationResult> UpdateTimeSheetAsync(string SessionId, Wfm.Admin.ClientServiceReference.TimeSheet candidateTimeSheet) {
            return base.Channel.UpdateTimeSheetAsync(SessionId, candidateTimeSheet);
        }
        
        public Wfm.Admin.ClientServiceReference.TimeSheetOperationResult ApproveTimeSheet(Wfm.Admin.ClientServiceReference.TimeSheetAndSession input) {
            return base.Channel.ApproveTimeSheet(input);
        }
        
        public System.Threading.Tasks.Task<Wfm.Admin.ClientServiceReference.TimeSheetOperationResult> ApproveTimeSheetAsync(Wfm.Admin.ClientServiceReference.TimeSheetAndSession input) {
            return base.Channel.ApproveTimeSheetAsync(input);
        }
        
        public Wfm.Admin.ClientServiceReference.PagedListResultOfTimeSheetHpUzpNkN ApproveTimeSheets(string sessionId, Wfm.Admin.ClientServiceReference.TimeSheetSlim[] timeSheets) {
            return base.Channel.ApproveTimeSheets(sessionId, timeSheets);
        }
        
        public System.Threading.Tasks.Task<Wfm.Admin.ClientServiceReference.PagedListResultOfTimeSheetHpUzpNkN> ApproveTimeSheetsAsync(string sessionId, Wfm.Admin.ClientServiceReference.TimeSheetSlim[] timeSheets) {
            return base.Channel.ApproveTimeSheetsAsync(sessionId, timeSheets);
        }
        
        public Wfm.Admin.ClientServiceReference.TimeSheetOperationResult RejectTimeSheet(Wfm.Admin.ClientServiceReference.TimeSheetAndSession input) {
            return base.Channel.RejectTimeSheet(input);
        }
        
        public System.Threading.Tasks.Task<Wfm.Admin.ClientServiceReference.TimeSheetOperationResult> RejectTimeSheetAsync(Wfm.Admin.ClientServiceReference.TimeSheetAndSession input) {
            return base.Channel.RejectTimeSheetAsync(input);
        }
        
        public Wfm.Admin.ClientServiceReference.TimeSheetOperationResult AddCandidateWorkTime(string sessionId, Wfm.Admin.ClientServiceReference.WorkTime workTime) {
            return base.Channel.AddCandidateWorkTime(sessionId, workTime);
        }
        
        public System.Threading.Tasks.Task<Wfm.Admin.ClientServiceReference.TimeSheetOperationResult> AddCandidateWorkTimeAsync(string sessionId, Wfm.Admin.ClientServiceReference.WorkTime workTime) {
            return base.Channel.AddCandidateWorkTimeAsync(sessionId, workTime);
        }
    }
}
